server:
  error:
    include-message: always
  port: 3002

spring:
  profiles:
    active: dev
  application:
    name: DEPARTMENT-SERVICE

#to include all our endpoints in the actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: dev
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/springsecurity
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true


  eureka:
    client:
      registry-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost

---

spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: Abuu001
    password: Abuu001
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true